# Generated by Django 4.2 on 2026-05-18 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('region', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('high_temp', models.FloatField()),
                ('low_temp', models.FloatField()),
                ('condition', models.CharField(choices=[('sunny', '☀️ Sunny'), ('cloudy', '☁️ Cloudy'), ('rainy', '🌧️ Rainy'), ('stormy', '⛈️ Stormy'), ('humid', '💨 Humid'), ('hazy', '🌫️ Hazy')], max_length=20)),
                ('rainfall_chance', models.IntegerField(default=0, help_text='Chance of rain (0-100)')),
                ('wind_speed', models.FloatField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='blog.city')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('city', 'date')},
            },
        ),
        migrations.CreateModel(
            name='WeatherAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('level', models.CharField(choices=[('info', 'ℹ️ Information'), ('warning', '⚠️ Warning'), ('alert', '🚨 Alert')], max_length=20)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='blog.city')),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(help_text='Temperature in Celsius')),
                ('feels_like', models.FloatField(help_text='Feels like temperature in Celsius')),
                ('humidity', models.IntegerField(help_text='Humidity percentage (0-100)')),
                ('wind_speed', models.FloatField(help_text='Wind speed in km/h')),
                ('condition', models.CharField(choices=[('sunny', '☀️ Sunny'), ('cloudy', '☁️ Cloudy'), ('rainy', '🌧️ Rainy'), ('stormy', '⛈️ Stormy'), ('humid', '💨 Humid'), ('hazy', '🌫️ Hazy')], max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='current_weather', to='blog.city')),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
